name: Update Azure WAF Policy with New IP

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

permissions:
  id-token: write
  contents: read      
jobs:
  update-waf-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure cli
      run: |
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install azure-cli

    # - name: Azure login
    #   uses: azure/login@v2
    #   with:
    #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #       client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       auth-type: IDENTITY
    
    - uses: azure/login@v2
      with:
<<<<<<< HEAD
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY

    - name: Export WAF Policy
      run: |
        az network front-door waf-policy show --resource-group Mithun-RG --policy-name azusctruuatwaf > policy.json

    - name: Modify WAF Policy (Add IPs to Existing Condition)
      run: |
        # This script modifies the policy.json to include new IPs under the existing condition.
        IPs="192.168.1.1 192.168.2.2 192.168.2.3 180.151.37.235"
        jq '.properties.rules[] | select(.name=="IPrestrictiontruuat") | .matchConditions[0].values += ['$IPs']' policy.json > updated_policy.json

    - name: Apply Updated WAF Policy
      run: |
        az network front-door waf-policy update --resource-group Mithun-RG --policy-name azusctruuatwaf --set @updated_policy.json

    - name: Clean up
      run: |
        rm policy.json updated_policy.json
